### Registrar ingreso de estudiante
POST http://localhost:8000/api/ingresos
Content-Type: application/json

{
  "codigoEstudiante": "201002",
  "nombreEstudiante": "Juaan Romero",
  "idPrograma": 2,
  "fechaIngreso": "2024-11-06",
  "horaIngreso": "07:00",
  "idSala": 1,
  "idResponsable": 1
}


### Registrar salida de estudiante
PUT http://localhost:8000/api/ingresos/6/salida
Content-Type: application/json

{
  "horaSalida": "09:00"
}

### mostrar ingresos del dia 
GET http://localhost:8000/api/ingresos/consulta??fechaInicio=2024-11-16&fechaFin=2024-11-20

###  modificar un ingreso en espesifico
PUT http://localhost:8000/api/ingresos/6
Content-Type: application/json

{
  "codigoEstudiante": "2021001",
  "nombreEstudiante": "Camilo Romero"
}

###mostrar otras tablas 
###mostrar programas
GET http://localhost:8000/api/programa
Content-Type: application/json

### mostrar salas
GET http://localhost:8000/api/sala
Content-Type: application/json

#### mostrar responsabble
GET http://localhost:8000/api/responsable
Content-Type: application/json




###registrar horario
POST http://localhost:8000/api/horarios-salas
Content-Type: application/json

{
  "idSala": 1,
  "dia": "viernes",
  "materia": "Matematicas",
  "horaInicio": "08:00",
  "horaFin": "10:00",
  "idPrograma": 2
}
###Consultar horarios:
GET http://localhost:8000/api/horarios-salas?idSala=1&dia=lunes

###Actualizar horario:
PUT http://localhost:8000/api/horarios-salas/2
Content-Type: application/json

{
  "horaInicio": "06:00",
  "horaFin": "07:00"
}


###eliminar horario:
DELETE http://localhost:8000/api/horarios-salas/1

